:- set_prolog_flag(answer_write_options,[max_depth(0)]).

:- PessoasBanco = [pessoa('Manuela Dias', ['camisa amarela', 'vestido de la', 'vestido de alcas']),
 pessoa('Manuela Arriaga', ['camisa verde', 'vestido de alcas']),
 pessoa('Jose Francisco', ['camisa vermelha', 'chapeu de abas']),
 pessoa('Miguel Branco', ['camisa branca', 'chapeu de abas']),
 pessoa('Abilio Santos', ['chapeu de coco', 'calcoes', 'peruca loura']),
 pessoa('Maria Venancio', ['camisa amarela', 'peruca negra', vestido]),
 pessoa('Tiburcio Silva', ['chapeu de palha', 'camisa aos quadrados', 'calcas a boca de sino']),
 pessoa('Maria Manuela', [vestido, sandalias, 'oculos']),
 pessoa('Joana Silva', ['vestido de alcas', boina, 'chapeu de palha']),
 pessoa('Miguel Silva', ['chapeu cowboy', 'calcoes', 'peruca negra']),
 pessoa('Joaquina Ambrosio', ['vestido de la', barba, 'camisola vermelha']),
 pessoa('Pedro Barata', ['calcas a boca de sino', 'camisa aos quadrados']),
 pessoa('Pedro Dias', ['camisa preta', 'calcas a boca de sino']),
 pessoa('Valentino Ferreira', [barba, tenis, 'calcas bootcut']),
 pessoa('Luis Brito', [barba, 'peruca loura', 'calcas bootcut']),
 pessoa('Francisco Marques', [tenis, 'calcas a boca de sino']),
 pessoa('Rosario Marques', ['botas neve', 'calcas a boca de sino']),
 pessoa('Antonio Torres', ['calcas a boca de sino', 'cabelo louro', 'peruca negra']),
 pessoa('Alice Teixeira', ['cabelo cinza', 'camisa preta', 'calcas bootcut']),
 pessoa('Laura Teixeira', ['cabelo cinza', 'vestido de noite']),
 pessoa('Maria Silva', ['chapeu de palha', calcas, 'peruca cinza']),
 pessoa('Maria Apolinaria', [calcas, 'peruca cinza', gorro]),
 pessoa('Luisa Ribeiro', [boina, 'camisa azul', mocassins]),
 pessoa('Alvaro Ribeiro', ['chapeu de coco', 'camisa preta', mocassins]),
 pessoa('Rui Mota', ['botas militares', 'camisa branca', tenis, 'peruca ruiva']),
 pessoa('Rodrigo Melo', ['oculos', 'botas neve', 'cabelo preto', 'camisa verde']),
 pessoa('Manuel Branco', ['peruca cinza', socas]),
 pessoa('Mariana Brito', ['calcas bootcut', 'camisa preta', 'peruca loura']),
 pessoa('Mario Branco', ['cabelo preto', barba, 'peruca ruiva']),
 pessoa('Graca Ribeiro', ['chapeu de palha', 'peruca branca']),
 pessoa('Eugenio Matos', ['calcas bootcut', 'camisa amarela', 'cabelo branco']),
 pessoa('David Ferreira', ['camisa preta', gorro, 'peruca cinza', 'cabelo louro']),
 pessoa('David Costa', [mocassins, 'chapeu cowboy', gorro]),
 pessoa('Michael Costa', [socas, 'peruca cinza', 'camisa branca', 'chapeu de abas']),
 pessoa('Dulce Ramos', [vestido, bone]),
 pessoa('Dulce Mota', ['botas de salto alto', 'camisa branca', 'calcoes']),
 pessoa('Anacleto Silva', ['botas militares', 'calcoes', 'chapeu de abas', bigode]),
 pessoa('Ana Ramos', [vestido, tenis, 'calcas a boca de sino', 'chapeu cowboy']),
 pessoa('Antonio Maria', ['camisa preta', 'calcoes', 'peruca ruiva']),
 pessoa('Eugenio Lopes', ['camisa branca', gorro, 'botas de salto alto']),
 pessoa('Tiburcio Ladrao', ['botas neve', oculos, 'peruca negra', bone]),
 pessoa('Miguel Lopes', ['peruca cinza', sandalias, boina, barba, 'oculos']),
 pessoa('Ana Branco', [boina, 'cabelo branco', 'camisa branca']),
 pessoa('Antonio Melo', ['chapeu de coco', 'botas neve', 'oculos', 'calcas a boca de sino']),
 pessoa('Maria Ferreira', ['camisa azul', 'botas neve', vestido, boina]),
 pessoa('Joaquim Lopes', [bigode,'peruca cinza', 'calcas a boca de sino', 'camisa verde']),
 pessoa('Jorge Armando', [bigode, 'camisa aos quadrados', 'peruca cinza', 'calcas a boca de sino']),
 pessoa('Vania Silva', ['chapeu de coco', oculos, 'vestido de alcas']),
 pessoa('Octavio Mendonca', ['chapeu de palha', 'botas neve', calcas, 'camisa verde']),
 pessoa('Joaquina Maria', [boina, 'camisa vermelha', 'calcas a boca de sino', 'vestido de alcas'])
 ],
 CaracteristicasCriminoso = ['peruca negra', bone, oculos, 'botas neve'],
 encontraSuspeitos(PessoasBanco, CaracteristicasCriminoso, Suspeitos),
 nl, nl, writeln('Suspeitos (dia 5):'),
 writeln(Suspeitos).
